"""Pentest hypothesis engine.

Every tool execution MUST be backed by a hypothesis derived from recon
evidence. This module reads the agent state (findings, tech_stack,
discovered URLs/params/headers, executed tool runs) and produces a list
of testable hypotheses. Each hypothesis is a concrete, falsifiable
statement of the form:

    "ON {target} WHERE {evidence} → TEST {skill} WITH {tool}
     EXPECTING {signal_expected}"

The supervisor consumes the highest-confidence pending hypothesis to
build the next pentest tactic. Without hypotheses → no tactic → no
tool execution. This kills "running tools in the dark".

Each hypothesis is a dict with these fields:

    id                    - stable hash (so we don't re-fire)
    family                - one of: sqli, xss, lfi, ssrf, redirect, crlf,
                                    xxe, rce, ssti, xslt, cors, csv,
                                    auth_bypass, info_disclosure, cms,
                                    weak_crypto
    target                - URL or asset the hypothesis applies to
    target_param          - query/header/body param name (or "")
    rationale             - human-readable WHY: which evidence triggered it
    evidence_signals      - keywords found in evidence that justify the H
    suggested_skill       - SKILL_CATALOG id
    suggested_tool        - kali tool name (must be installed)
    suggested_extra_args  - per-tool argv overrides ({"sqlmap": [...]})
    signal_expected       - what success in the response looks like
    confidence            - 0.0..1.0 score
    learning_id           - reference to the VulnerabilityLearning row
                            that backs the technique (optional)

Hypotheses are generated by rule-based matchers over evidence
(regex-grade rules + tech-stack overlap). LLM-driven hypothesis
generation can plug in later via the same dict schema.
"""
from __future__ import annotations

import hashlib
import logging
import re
from typing import Any, Iterable
from urllib.parse import urlparse, parse_qs

logger = logging.getLogger(__name__)


# Parameter name heuristics — used by SSRF/redirect/CRLF/file-include rules.
SSRF_PARAM_HINTS = (
    "url", "uri", "link", "src", "source", "redirect", "redir", "next",
    "callback", "return", "returnto", "return_to", "image", "img", "img_url",
    "webhook", "api", "feed", "rss", "site", "path", "file", "doc",
)
SQLI_PARAM_HINTS = (
    "id", "uid", "pid", "user_id", "userid", "search", "q", "query",
    "keyword", "keywords", "name", "category", "cat", "page", "p",
    "filter", "order", "sort", "month", "year", "ref",
)
XSS_REFLECTED_HINTS = (
    "q", "query", "search", "s", "keyword", "name", "username", "email",
    "comment", "title", "subject", "msg", "message", "lang", "locale",
)
LFI_PARAM_HINTS = (
    "file", "path", "include", "page", "template", "lang", "doc", "view",
    "show", "read", "load", "filename",
)
CMD_PARAM_HINTS = ("cmd", "exec", "command", "ping", "host", "ip", "domain")


def _iter_evidence_blobs(findings: Iterable[dict[str, Any]]) -> Iterable[tuple[dict[str, Any], str]]:
    """Yield (finding, blob) pairs. Blob is a concatenation of textual surfaces."""
    for finding in findings or []:
        if not isinstance(finding, dict):
            continue
        details = finding.get("details") or {}
        parts = [
            str(finding.get("title") or ""),
            str(details.get("evidence") or "") if isinstance(details, dict) else "",
            str(details.get("stdout") or "") if isinstance(details, dict) else "",
            str(details.get("http_headers_raw") or "") if isinstance(details, dict) else "",
            str(details.get("url") or "") if isinstance(details, dict) else "",
            str(details.get("asset") or "") if isinstance(details, dict) else "",
        ]
        yield finding, "\n".join(p for p in parts if p)


def _extract_urls_from_findings(findings: list[dict[str, Any]]) -> list[str]:
    """Best-effort URL extraction from finding details."""
    urls: set[str] = set()
    url_re = re.compile(r"https?://[^\s'\"<>)]+", re.IGNORECASE)
    for finding, blob in _iter_evidence_blobs(findings):
        details = finding.get("details") or {}
        if isinstance(details, dict):
            for key in ("url", "asset", "endpoint", "location"):
                v = details.get(key)
                if isinstance(v, str) and v.startswith(("http://", "https://")):
                    urls.add(v)
        urls.update(url_re.findall(blob))
    return sorted(urls)


def _params_in_url(url: str) -> list[str]:
    try:
        return sorted(parse_qs(urlparse(url).query).keys())
    except Exception:
        return []


def _h_id(*parts: str) -> str:
    seed = "|".join(p for p in parts if p)
    return "h-" + hashlib.sha1(seed.encode("utf-8")).hexdigest()[:12]


def _stack_contains(stack: set[str], *needles: str) -> bool:
    return any(n in stack for n in needles)


def extract_pentest_hypotheses(state: dict[str, Any]) -> list[dict[str, Any]]:
    """Build the list of pending hypotheses from current agent state.

    Idempotent: repeated calls yield the same ids for the same evidence,
    so the supervisor can dedupe without losing context.
    """
    findings = list(state.get("vulnerabilidades_encontradas") or [])
    tech_stack = {str(t).strip().lower() for t in (state.get("detected_tech_stack") or []) if str(t).strip()}
    target = str(state.get("target") or "")
    urls = list(state.get("lista_ativos") or [])
    urls.extend(_extract_urls_from_findings(findings))
    if target:
        urls.append(target)
    urls = sorted({u.strip() for u in urls if u.strip()})

    evidence_blobs = list(_iter_evidence_blobs(findings))
    haystack = "\n".join(blob for _, blob in evidence_blobs).lower()

    hypotheses: list[dict[str, Any]] = []
    seen_ids: set[str] = set()

    def _push(h: dict[str, Any]) -> None:
        hid = h.get("id") or _h_id(h.get("family", ""), h.get("target", ""), h.get("target_param", ""))
        h["id"] = hid
        if hid in seen_ids:
            return
        seen_ids.add(hid)
        hypotheses.append(h)

    # ── H1: SQLi by stack — ASP.NET/MSSQL or PHP/MySQL ────────────────────
    if _stack_contains(tech_stack, "asp.net", "iis", "mssql"):
        for url in urls:
            for p in _params_in_url(url):
                if p.lower() in SQLI_PARAM_HINTS:
                    _push({
                        "family": "sqli",
                        "target": url,
                        "target_param": p,
                        "rationale": (
                            f"Stack ASP.NET/IIS/MSSQL detectado + parametro '{p}' na URL. "
                            f"Endpoints ASP classicos concatenam input em SQL."
                        ),
                        "evidence_signals": sorted(tech_stack & {"asp.net", "iis", "mssql"}),
                        "suggested_skill": "vuln-injection",
                        "suggested_tool": "sqlmap",
                        "suggested_extra_args": {
                            "sqlmap": ["--dbms=mssql", "--batch", "--level=5", "--risk=3", "--random-agent"],
                            "wapiti": ["-m", "sql,blindsql", "-f", "json"],
                        },
                        "signal_expected": "WAITFOR DELAY '0:0:10' resulta em latency >10s OU body retorna @@version OR sqlmap loga 'injectable'",
                        "confidence": 0.92,
                    })
    if _stack_contains(tech_stack, "php", "mysql", "mariadb"):
        for url in urls:
            for p in _params_in_url(url):
                if p.lower() in SQLI_PARAM_HINTS:
                    _push({
                        "family": "sqli",
                        "target": url,
                        "target_param": p,
                        "rationale": f"Stack PHP/MySQL + param '{p}' (classico SQLi vector).",
                        "evidence_signals": sorted(tech_stack & {"php", "mysql", "mariadb"}),
                        "suggested_skill": "vuln-injection",
                        "suggested_tool": "sqlmap",
                        "suggested_extra_args": {
                            "sqlmap": ["--dbms=mysql", "--batch", "--level=5", "--risk=3"],
                        },
                        "signal_expected": "SLEEP(10) latency, error msg 'You have an error in your SQL syntax'",
                        "confidence": 0.88,
                    })

    # ── H2: XSS reflected (parametros tipicos) ────────────────────────────
    for url in urls:
        for p in _params_in_url(url):
            if p.lower() in XSS_REFLECTED_HINTS:
                _push({
                    "family": "xss",
                    "target": url,
                    "target_param": p,
                    "rationale": f"Parametro '{p}' tipicamente refletido em paginas (search/comment/name).",
                    "evidence_signals": [p.lower()],
                    "suggested_skill": "vuln-injection",
                    "suggested_tool": "dalfox",
                    "suggested_extra_args": {
                        "dalfox": ["--silence", "--skip-bav", "--skip-mining-dom", "--no-spinner"],
                    },
                    "signal_expected": "Payload literal aparece no body OU dalfox loga POC verificado",
                    "confidence": 0.75,
                })

    # ── H3: SSRF + open redirect + CRLF (?url, ?next, ?redirect) ──────────
    for url in urls:
        for p in _params_in_url(url):
            if p.lower() in SSRF_PARAM_HINTS:
                _push({
                    "family": "ssrf",
                    "target": url,
                    "target_param": p,
                    "rationale": f"Param '{p}' tipicamente carrega URL alvo (vetor SSRF/redirect/CRLF).",
                    "evidence_signals": [p.lower()],
                    "suggested_skill": "vuln-ssrf-redirect",
                    "suggested_tool": "curl-headers",
                    "suggested_extra_args": {},
                    "signal_expected": "Resposta contem instance-id (AWS metadata) OR Location: para dominio externo OR header injetado (CRLF)",
                    "confidence": 0.82,
                })

    # ── H4: LFI / path traversal ──────────────────────────────────────────
    for url in urls:
        for p in _params_in_url(url):
            if p.lower() in LFI_PARAM_HINTS:
                _push({
                    "family": "lfi",
                    "target": url,
                    "target_param": p,
                    "rationale": f"Param '{p}' classico de file inclusion.",
                    "evidence_signals": [p.lower()],
                    "suggested_skill": "vuln-injection",
                    "suggested_tool": "wapiti",
                    "suggested_extra_args": {"wapiti": ["-m", "file", "-f", "json"]},
                    "signal_expected": "/etc/passwd contents OR base64 source via php://filter",
                    "confidence": 0.78,
                })

    # ── H5: Command injection (cmd/host/ping params) ──────────────────────
    for url in urls:
        for p in _params_in_url(url):
            if p.lower() in CMD_PARAM_HINTS:
                _push({
                    "family": "rce",
                    "target": url,
                    "target_param": p,
                    "rationale": f"Param '{p}' tipicamente passado a system() (ping/cmd/exec).",
                    "evidence_signals": [p.lower()],
                    "suggested_skill": "vuln-injection",
                    "suggested_tool": "curl-headers",
                    "suggested_extra_args": {},
                    "signal_expected": "uid output OR pingback OOB via interactsh",
                    "confidence": 0.80,
                })

    # ── H6: CORS misconfig (evidencia em header) ──────────────────────────
    if "access-control-allow-origin" in haystack and "access-control-allow-credentials" in haystack:
        _push({
            "family": "cors",
            "target": target or (urls[0] if urls else ""),
            "target_param": "",
            "rationale": "Evidencia de headers CORS na resposta — provavel reflexao de Origin com credentials.",
            "evidence_signals": ["access-control-allow-origin", "access-control-allow-credentials"],
            "suggested_skill": "tech-http-fingerprint",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "ACAO==Origin atacante AND ACAC=true",
            "confidence": 0.70,
        })

    # ── H7: Shellshock (cgi-bin no path) ──────────────────────────────────
    for url in urls:
        if "/cgi-bin/" in url.lower():
            _push({
                "family": "rce",
                "target": url,
                "target_param": "User-Agent",
                "rationale": "Caminho /cgi-bin/ encontrado — alvo classico Shellshock.",
                "evidence_signals": ["/cgi-bin/"],
                "suggested_skill": "vuln-injection",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": "() { :;}; echo retorna id no body OU pingback OOB",
                "confidence": 0.85,
            })

    # ── H8: WordPress (wpscan) ────────────────────────────────────────────
    if "wordpress" in tech_stack or "wp-content" in haystack or "wp-admin" in haystack:
        for url in urls[:3]:
            _push({
                "family": "cms",
                "target": url,
                "target_param": "",
                "rationale": "WordPress detectado (wp-content/wp-admin OU tech_stack).",
                "evidence_signals": ["wordpress"],
                "suggested_skill": "tech-cms-fingerprint",
                "suggested_tool": "wpscan",
                "suggested_extra_args": {"wpscan": ["--enumerate", "u,vp,vt", "--random-user-agent"]},
                "signal_expected": "Plugins vulneraveis, usuarios enumerados, xmlrpc accessible",
                "confidence": 0.90,
            })

    # ── H9: XXE (Content-Type XML aceito) ─────────────────────────────────
    if "application/xml" in haystack or "text/xml" in haystack or "soapaction" in haystack:
        _push({
            "family": "xxe",
            "target": target or (urls[0] if urls else ""),
            "target_param": "body (XML)",
            "rationale": "Servidor aceita Content-Type XML/SOAP — vetor XXE.",
            "evidence_signals": ["application/xml", "text/xml", "soapaction"],
            "suggested_skill": "vuln-injection",
            "suggested_tool": "wapiti",
            "suggested_extra_args": {"wapiti": ["-m", "xxe", "-f", "json"]},
            "signal_expected": "/etc/passwd no body OR callback OOB no interactsh",
            "confidence": 0.78,
        })

    # ── H10: Open redirect / CRLF (?next, redirect, with no SSRF tag) ─────
    # Already captured under H3 (ssrf family). Add a dedicated redirect H
    # for high-confidence Location-header reflection observed in evidence.
    if "location:" in haystack and ("redirect" in haystack or "location: http" in haystack):
        for url in urls[:2]:
            _push({
                "family": "redirect",
                "target": url,
                "target_param": "url|next|redirect",
                "rationale": "Header Location: aparece em evidencia + URL tem param de redirecionamento.",
                "evidence_signals": ["location:", "redirect"],
                "suggested_skill": "vuln-ssrf-redirect",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": "Location: para dominio externo do atacante",
                "confidence": 0.65,
            })

    # ── H11: SSTI (Jinja/Twig/Ruby template engine indicators) ────────────
    if any(s in haystack for s in ("jinja", "twig", "freemarker", "erb", "smarty", "x-powered-by: express")):
        _push({
            "family": "ssti",
            "target": target or (urls[0] if urls else ""),
            "target_param": "any reflected field",
            "rationale": "Engine de template detectado (Jinja/Twig/FreeMarker/ERB) — possivel SSTI.",
            "evidence_signals": ["jinja", "twig", "freemarker", "erb"],
            "suggested_skill": "vuln-injection",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "{{7*'7'}} renderiza 49 (Twig) ou 7777777 (Jinja)",
            "confidence": 0.70,
        })

    # ── H12: Information disclosure — .git/web.config/.env ────────────────
    if any(s in haystack for s in (".git", "web.config", ".env", "phpinfo", "stack trace")):
        _push({
            "family": "info_disclosure",
            "target": target or (urls[0] if urls else ""),
            "target_param": "",
            "rationale": "Evidencia de exposicao sensivel (.git/.env/web.config/stacktrace).",
            "evidence_signals": [".git", "web.config", ".env", "phpinfo"],
            "suggested_skill": "vuln-information-disclosure",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "Status 200 em /.git/config OR /web.config OR /phpinfo.php",
            "confidence": 0.85,
        })

    return hypotheses


def hypothesis_for_skill(
    hypotheses: list[dict[str, Any]],
    *,
    skill_id: str | None = None,
    family: str | None = None,
) -> dict[str, Any] | None:
    """Return the highest-confidence hypothesis matching the filters, or None."""
    candidates = []
    for h in hypotheses or []:
        if skill_id and str(h.get("suggested_skill") or "") != skill_id:
            continue
        if family and str(h.get("family") or "") != family:
            continue
        candidates.append(h)
    candidates.sort(key=lambda x: -float(x.get("confidence") or 0))
    return candidates[0] if candidates else None


def hypothesis_to_tactic(h: dict[str, Any], capability: str = "risk_assessment") -> dict[str, Any]:
    """Materialise a hypothesis as a pentest tactic the supervisor can lock to."""
    return {
        "tactic_id": f"hypothesis:{h['family']}:{h['id']}",
        "skill_id": str(h.get("suggested_skill") or "vuln-injection"),
        "capability": capability,
        "objective": h.get("rationale", ""),
        "hypothesis": h.get("rationale", ""),
        "allowed_tools": [str(h.get("suggested_tool") or "")],
        "preferred_tool": str(h.get("suggested_tool") or ""),
        "extra_args": dict(h.get("suggested_extra_args") or {}),
        "strategy_source": "hypothesis_engine",
        "strategy_score": int(round(float(h.get("confidence") or 0) * 100)),
        "learning_techniques": [],
        "evidence_required": [h.get("signal_expected", "")],
        "constraints": [],
        "phase_refs": [],
        "targets": [str(h.get("target") or "")] if h.get("target") else [],
        "reason": (
            f"Hipotese {h.get('family')} sobre {h.get('target')}"
            + (f"?{h.get('target_param')}=" if h.get("target_param") else "")
            + f" — {h.get('rationale','')} (confidence={h.get('confidence',0):.2f})"
        ),
    }
