"""Pentest hypothesis engine.

Every tool execution MUST be backed by a hypothesis derived from recon
evidence. This module reads the agent state (findings, tech_stack,
discovered URLs/params/headers, executed tool runs) and produces a list
of testable hypotheses. Each hypothesis is a concrete, falsifiable
statement of the form:

    "ON {target} WHERE {evidence} → TEST {skill} WITH {tool}
     EXPECTING {signal_expected}"

The supervisor consumes the highest-confidence pending hypothesis to
build the next pentest tactic. Without hypotheses → no tactic → no
tool execution. This kills "running tools in the dark".

Each hypothesis is a dict with these fields:

    id                    - stable hash (so we don't re-fire)
    family                - one of: sqli, xss, lfi, ssrf, redirect, crlf,
                                    xxe, rce, ssti, xslt, cors, csv,
                                    auth_bypass, info_disclosure, cms,
                                    weak_crypto
    target                - URL or asset the hypothesis applies to
    target_param          - query/header/body param name (or "")
    rationale             - human-readable WHY: which evidence triggered it
    evidence_signals      - keywords found in evidence that justify the H
    suggested_skill       - SKILL_CATALOG id
    suggested_tool        - kali tool name (must be installed)
    suggested_extra_args  - per-tool argv overrides ({"sqlmap": [...]})
    signal_expected       - what success in the response looks like
    confidence            - 0.0..1.0 score
    learning_id           - reference to the VulnerabilityLearning row
                            that backs the technique (optional)

Hypotheses are generated by rule-based matchers over evidence
(regex-grade rules + tech-stack overlap). LLM-driven hypothesis
generation can plug in later via the same dict schema.
"""
from __future__ import annotations

import hashlib
import logging
import re
from typing import Any, Iterable
from urllib.parse import urlparse, parse_qs

logger = logging.getLogger(__name__)


# Parameter name heuristics — used by SSRF/redirect/CRLF/file-include rules.
SSRF_PARAM_HINTS = (
    "url", "uri", "link", "src", "source", "redirect", "redir", "next",
    "callback", "return", "returnto", "return_to", "image", "img", "img_url",
    "webhook", "api", "feed", "rss", "site", "path", "file", "doc",
)
SQLI_PARAM_HINTS = (
    "id", "uid", "pid", "user_id", "userid", "search", "q", "query",
    "keyword", "keywords", "name", "category", "cat", "page", "p",
    "filter", "order", "sort", "month", "year", "ref",
)
XSS_REFLECTED_HINTS = (
    "q", "query", "search", "s", "keyword", "name", "username", "email",
    "comment", "title", "subject", "msg", "message", "lang", "locale",
)
LFI_PARAM_HINTS = (
    "file", "path", "include", "page", "template", "lang", "doc", "view",
    "show", "read", "load", "filename",
)
CMD_PARAM_HINTS = ("cmd", "exec", "command", "ping", "host", "ip", "domain")

# ─────────────────────────────────────────────────────────────────────
# PARAM × INJECTION-FAMILY MATRIX
# Every discovered parameter is mapped to ALL applicable injection
# families. Source: user-defined principle + EdOverflow/coffinxp +
# OWASP API Top 10 (BOLA/BFLA).
# Each entry is (regex matching param name) -> set of family ids.
#
# Family taxonomy (used by recipes below):
#   sqli, xss, lfi, rfi, ssrf, redirect, crlf, xxe, ssti, rce,
#   command_injection, csrf, csv_injection, type_juggle, idor, bola,
#   bfla, mass_assign, auth_bypass, info_disclosure, prototype_pollution,
#   graphql_introspection, deserialization, jwt_attack, oauth_abuse
# ─────────────────────────────────────────────────────────────────────
PARAM_INJECTION_MATRIX: list[tuple[re.Pattern[str], set[str]]] = [
    # search/query — refletivo + concatenado em SQL
    (re.compile(r"^(?:q|s|qs|search|query|keyword|keywords|kw|term|find|lookup)$", re.I),
     {"sqli", "xss", "lfi", "ssti", "rce"}),
    # numeric identifiers — SQLi, IDOR, BOLA, mass-assign. The id-family
    # almost ALWAYS deserves an IDOR/BOLA probe even when SQLi is the
    # first instinct: many APIs sanitize SQL but forget ownership checks.
    (re.compile(r"^(?:id|uid|pid|sid|cid|tid|user_?id|account_?id|order_?id|item_?id|product_?id|page|p|num|number)$", re.I),
     {"sqli", "idor", "bola", "mass_assign"}),
    # name/title/desc — stored XSS, SSTI, CSV-injection
    (re.compile(r"^(?:name|title|first_?name|last_?name|description|desc|bio|nickname|displayname|comment|note|body|content|label|subject|msg|message)$", re.I),
     {"xss", "ssti", "csv_injection", "sqli"}),
    # auth fields — SQLi + NoSQL + type juggling + BOLA when login enumerates
    (re.compile(r"^(?:user|username|login|email|mail|account|signin|userid)$", re.I),
     {"auth_bypass", "sqli", "xss", "idor"}),
    (re.compile(r"^(?:pass|pwd|password|passwd|pin|secret)$", re.I),
     {"auth_bypass", "type_juggle"}),
    # URL-bearing params — SSRF + open redirect + CRLF
    (re.compile(r"^(?:url|uri|link|src|source|target|redirect|redir|next|continue|return|returnto|return_?to|callback|cb|image|img|img_?url|webhook|api|feed|rss|site|destination|dest)$", re.I),
     {"ssrf", "redirect", "crlf"}),
    # file/path — LFI + RFI + path traversal + IDOR on file-by-id endpoints
    (re.compile(r"^(?:file|filename|path|page|template|lang|doc|view|show|read|load|include|require|resource|content_?path|src_?path|attachment|attachment_?id)$", re.I),
     {"lfi", "rfi", "ssrf", "idor"}),
    # command-execution params
    (re.compile(r"^(?:cmd|exec|run|command|action|task|do|fn|fun|func|callback|ping|host|ip|domain|server|address)$", re.I),
     {"rce", "command_injection", "ssti"}),
    # template-bearing — SSTI
    (re.compile(r"^(?:template|tpl|tmpl|view|render|skin|theme|design|layout)$", re.I),
     {"ssti", "lfi"}),
    # XML/SOAP/data — XXE + deserialization
    (re.compile(r"^(?:xml|soap|data|payload|body|envelope|request_?body|serialized|object)$", re.I),
     {"xxe", "deserialization", "rce", "ssti"}),
    # admin/role/privilege — mass-assignment + BFLA
    (re.compile(r"^(?:role|is_?admin|admin|priv|privilege|access_?level|permission|superuser|root|tenant_?id|org_?id|owner_?id|company_?id|workspace_?id)$", re.I),
     {"mass_assign", "bfla", "idor", "bola"}),
    # CSRF-like tokens (likely bypassable when missing/forgable)
    (re.compile(r"^(?:csrf|csrf_?token|_token|xsrf|antiforgery|state|nonce)$", re.I),
     {"csrf"}),
    # JSONP / callback patterns
    (re.compile(r"^(?:callback|jsonp|json_?callback|cb|on_?success)$", re.I),
     {"xss", "ssrf"}),
    # JWT / OAuth tokens — alg=none, weak HMAC, kid injection
    (re.compile(r"^(?:token|jwt|access_?token|id_?token|refresh_?token|bearer|auth_?token)$", re.I),
     {"jwt_attack", "oauth_abuse", "auth_bypass"}),
    # GraphQL introspection / batched queries
    (re.compile(r"^(?:query|gql|graphql|operation|operationName)$", re.I),
     {"graphql_introspection", "sqli", "ssti"}),
    # JS-side polluted attribute prototype assignment
    (re.compile(r"^(?:__proto__|constructor|prototype)$", re.I),
     {"prototype_pollution"}),
    # debug / test / hidden — info disclosure intent
    (re.compile(r"^(?:debug|test|dev|verbose|trace|profile|env|environment|mode|stage)$", re.I),
     {"info_disclosure", "rce"}),
]

# Hidden parameters to probe even when not observed in the code-analyzer
# output. These are universally worth a probe in any application.
HIDDEN_PARAM_PROBES = (
    "debug", "test", "dev", "admin", "is_admin", "role",
    "source", "show_source", "verbose", "trace",
    "_method", "_action", "callback", "jsonp",
)

# Header injection matrix — every request should test these, especially
# in EXPLOITATION stage where auth/access-control bugs hide.
HEADER_INJECTION_MATRIX: dict[str, str] = {
    "X-Forwarded-For":          "127.0.0.1",
    "X-Forwarded-Host":         "evil.example.com",
    "X-Original-URL":           "/admin",
    "X-Rewrite-URL":            "/admin",
    "X-HTTP-Method-Override":   "PUT",
    "X-Method-Override":        "DELETE",
    "X-Custom-IP-Authorization": "127.0.0.1",
    "Host":                     "evil.example.com",
    "Referer":                  "https://attacker.example/",
    "User-Agent":               "() { :; }; echo SHELLSHOCK",
}

VERB_TAMPERING_PROBES = ("OPTIONS", "PUT", "DELETE", "PATCH", "TRACE")


# ─────────────────────────────────────────────────────────────────────
# FAMILY → RECIPE: skill_id, tool, extra_args, signal_expected, confidence
# Every entry maps an injection family to the concrete test recipe.
# ─────────────────────────────────────────────────────────────────────
FAMILY_RECIPES: dict[str, dict[str, Any]] = {
    "sqli": {
        "skill": "vuln-injection", "tool": "sqlmap",
        "extra_args": {"sqlmap": ["--batch", "--level=5", "--risk=3", "--random-agent"]},
        "signal": "sqlmap loga 'injectable' OU WAITFOR/SLEEP latency >5s OU @@version visivel",
        "confidence": 0.85,
    },
    "xss": {
        "skill": "vuln-injection", "tool": "dalfox",
        "extra_args": {"dalfox": ["--silence", "--skip-bav", "--skip-mining-dom", "--no-spinner"]},
        "signal": "payload literal aparece no body OU dalfox loga POC verificado",
        "confidence": 0.75,
    },
    "lfi": {
        "skill": "vuln-injection", "tool": "wapiti",
        "extra_args": {"wapiti": ["-m", "file", "-f", "json"]},
        "signal": "/etc/passwd content OU php://filter base64 source disclosure",
        "confidence": 0.75,
    },
    "rfi": {
        "skill": "vuln-injection", "tool": "wapiti",
        "extra_args": {"wapiti": ["-m", "file", "-f", "json"]},
        "signal": "Resposta contem conteudo de http://attacker controlado",
        "confidence": 0.65,
    },
    "ssrf": {
        "skill": "vuln-ssrf-redirect", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Body retorna instance-id (AWS metadata) OR callback OOB no interactsh",
        "confidence": 0.78,
    },
    "redirect": {
        "skill": "vuln-ssrf-redirect", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Location: para dominio externo do atacante (//evil, /\\evil)",
        "confidence": 0.72,
    },
    "crlf": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Header injetado %0d%0aX-Test:1 aparece na resposta (curl -D -)",
        "confidence": 0.68,
    },
    "xxe": {
        "skill": "vuln-injection", "tool": "wapiti",
        "extra_args": {"wapiti": ["-m", "xxe", "-f", "json"]},
        "signal": "/etc/passwd content OR OOB DTD callback",
        "confidence": 0.70,
    },
    "ssti": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "{{7*'7'}} renderiza 49 (Twig) ou 7777777 (Jinja)",
        "confidence": 0.68,
    },
    "rce": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Saida de id/uname no body OR pingback OOB",
        "confidence": 0.72,
    },
    "command_injection": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "id/uname output OR pingback (;,|,&&,||,$(),`)",
        "confidence": 0.72,
    },
    "csrf": {
        "skill": "vuln-auth-bypass", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Request sem token aceita OR token sem binding a sessao",
        "confidence": 0.65,
    },
    "csv_injection": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Field '=cmd|...' aparece literal no CSV exportado",
        "confidence": 0.60,
    },
    "type_juggle": {
        "skill": "vuln-auth-bypass", "tool": "curl-headers",
        "extra_args": {},
        "signal": "password como {\"$ne\":null} OU boolean true permite login",
        "confidence": 0.72,
    },
    "idor": {
        "skill": "vuln-idor-access-control", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Trocando id por outro retorna dados de outro usuario (200 + dados alheios)",
        "confidence": 0.80,
    },
    "bola": {
        # Broken Object Level Authorization — OWASP API#1. Same as IDOR
        # but specifically on REST/GraphQL object endpoints.
        "skill": "vuln-idor-access-control", "tool": "curl-headers",
        "extra_args": {},
        "signal": "GET /api/objects/{other_user_id} retorna 200 sem ownership check",
        "confidence": 0.80,
    },
    "bfla": {
        # Broken Function Level Authorization — OWASP API#5.
        "skill": "vuln-auth-bypass", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Endpoint /admin/* acessivel para usuario nao-admin OR role escala",
        "confidence": 0.75,
    },
    "mass_assign": {
        "skill": "vuln-auth-bypass", "tool": "curl-headers",
        "extra_args": {},
        "signal": "POST com extra field 'role:admin' aceita e persiste no perfil",
        "confidence": 0.72,
    },
    "auth_bypass": {
        "skill": "vuln-auth-bypass", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Login com ' OR 1=1-- ou X-Forwarded-For:127.0.0.1 obtem sessao",
        "confidence": 0.75,
    },
    "info_disclosure": {
        "skill": "vuln-information-disclosure", "tool": "curl-headers",
        "extra_args": {},
        "signal": "?debug=1 retorna stacktrace, OR /.git/config = 200, OR /web.config visivel",
        "confidence": 0.65,
    },
    "prototype_pollution": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "POST {\"__proto__\":{\"polluted\":1}} reflete em outro endpoint",
        "confidence": 0.55,
    },
    "graphql_introspection": {
        "skill": "vuln-api-graphql", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Query __schema retorna types/queries/mutations OU batch query causa DoS",
        "confidence": 0.78,
    },
    "deserialization": {
        "skill": "vuln-injection", "tool": "curl-headers",
        "extra_args": {},
        "signal": "Java serialized blob (rO0AB) ou PHP O: encontrado em request body",
        "confidence": 0.60,
    },
    "jwt_attack": {
        "skill": "vuln-auth-bypass", "tool": "jwt_tool",
        "extra_args": {},
        "signal": "JWT alg=none ou HS256 secret quebrado por wordlist",
        "confidence": 0.75,
    },
    "oauth_abuse": {
        "skill": "vuln-auth-bypass", "tool": "curl-headers",
        "extra_args": {},
        "signal": "redirect_uri aceita dominio attacker OU state ausente",
        "confidence": 0.70,
    },
}


def _families_for_param(param_name: str) -> set[str]:
    """Return ALL families that should be tested against this param name."""
    name = str(param_name or "").strip()
    if not name:
        return set()
    families: set[str] = set()
    for pat, fams in PARAM_INJECTION_MATRIX:
        if pat.search(name):
            families.update(fams)
    return families


def _iter_evidence_blobs(findings: Iterable[dict[str, Any]]) -> Iterable[tuple[dict[str, Any], str]]:
    """Yield (finding, blob) pairs. Blob is a concatenation of textual surfaces."""
    for finding in findings or []:
        if not isinstance(finding, dict):
            continue
        details = finding.get("details") or {}
        parts = [
            str(finding.get("title") or ""),
            str(details.get("evidence") or "") if isinstance(details, dict) else "",
            str(details.get("stdout") or "") if isinstance(details, dict) else "",
            str(details.get("http_headers_raw") or "") if isinstance(details, dict) else "",
            str(details.get("url") or "") if isinstance(details, dict) else "",
            str(details.get("asset") or "") if isinstance(details, dict) else "",
        ]
        yield finding, "\n".join(p for p in parts if p)


def _extract_urls_from_findings(findings: list[dict[str, Any]]) -> list[str]:
    """Best-effort URL extraction from finding details."""
    urls: set[str] = set()
    url_re = re.compile(r"https?://[^\s'\"<>)]+", re.IGNORECASE)
    for finding, blob in _iter_evidence_blobs(findings):
        details = finding.get("details") or {}
        if isinstance(details, dict):
            for key in ("url", "asset", "endpoint", "location"):
                v = details.get(key)
                if isinstance(v, str) and v.startswith(("http://", "https://")):
                    urls.add(v)
        urls.update(url_re.findall(blob))
    return sorted(urls)


def _params_in_url(url: str) -> list[str]:
    try:
        return sorted(parse_qs(urlparse(url).query).keys())
    except Exception:
        return []


def _h_id(*parts: str) -> str:
    seed = "|".join(p for p in parts if p)
    return "h-" + hashlib.sha1(seed.encode("utf-8")).hexdigest()[:12]


def _stack_contains(stack: set[str], *needles: str) -> bool:
    return any(n in stack for n in needles)


def extract_pentest_hypotheses(state: dict[str, Any]) -> list[dict[str, Any]]:
    """Build the list of pending hypotheses from current agent state.

    Idempotent: repeated calls yield the same ids for the same evidence,
    so the supervisor can dedupe without losing context.
    """
    findings = list(state.get("vulnerabilidades_encontradas") or [])
    tech_stack = {str(t).strip().lower() for t in (state.get("detected_tech_stack") or []) if str(t).strip()}
    target = str(state.get("target") or "")
    urls = list(state.get("lista_ativos") or [])
    urls.extend(_extract_urls_from_findings(findings))
    if target:
        urls.append(target)
    urls = sorted({u.strip() for u in urls if u.strip()})

    evidence_blobs = list(_iter_evidence_blobs(findings))
    haystack = "\n".join(blob for _, blob in evidence_blobs).lower()

    hypotheses: list[dict[str, Any]] = []
    seen_ids: set[str] = set()

    def _push(h: dict[str, Any]) -> None:
        hid = h.get("id") or _h_id(h.get("family", ""), h.get("target", ""), h.get("target_param", ""))
        h["id"] = hid
        if hid in seen_ids:
            return
        seen_ids.add(hid)
        hypotheses.append(h)

    def _push_matrix(*, target: str, param: str, families: set[str], rationale_extra: str = "",
                     confidence_boost: float = 0.0) -> None:
        """Generate a hypothesis per family for the given (target, param)."""
        for fam in families:
            recipe = FAMILY_RECIPES.get(fam)
            if not recipe:
                continue
            base_conf = float(recipe.get("confidence") or 0.7)
            conf = min(0.99, max(0.05, base_conf + confidence_boost))
            _push({
                "family": fam,
                "target": target,
                "target_param": param,
                "rationale": (
                    f"Param '{param}' compativel com familia '{fam}'. {rationale_extra}".strip()
                ),
                "evidence_signals": [param] if param else [],
                "suggested_skill": recipe.get("skill"),
                "suggested_tool": recipe.get("tool"),
                "suggested_extra_args": dict(recipe.get("extra_args") or {}),
                "signal_expected": recipe.get("signal", ""),
                "confidence": round(conf, 2),
            })

    # ── H1: PARAM × INJECTION-FAMILY MATRIX ───────────────────────────────
    # For every URL param + every form input, generate one hypothesis per
    # family the matrix says is applicable. This replaces the old single-
    # family-per-param rules — the same param can be vulnerable to many.
    sqli_stack_args: dict[str, list[str]] = {}
    stack_boost = 0.0
    rationale_stack = ""
    if _stack_contains(tech_stack, "asp.net", "iis", "mssql"):
        sqli_stack_args = {
            "sqlmap": ["--dbms=mssql", "--batch", "--level=5", "--risk=3", "--random-agent"],
            "wapiti": ["-m", "sql,blindsql", "-f", "json"],
        }
        stack_boost = 0.10
        rationale_stack = "Stack ASP.NET/IIS/MSSQL detectado — payloads MSSQL prioritarios."
    elif _stack_contains(tech_stack, "php", "mysql", "mariadb"):
        sqli_stack_args = {"sqlmap": ["--dbms=mysql", "--batch", "--level=5", "--risk=3"]}
        stack_boost = 0.08
        rationale_stack = "Stack PHP/MySQL — payloads MySQL prioritarios."

    # URL query params
    for url in urls:
        for p in _params_in_url(url):
            families = _families_for_param(p)
            if not families:
                # Even unknown-name params get a minimal probe set: SQLi+XSS+SSRF
                families = {"sqli", "xss"}
            _push_matrix(
                target=url, param=p, families=families,
                rationale_extra=rationale_stack,
                confidence_boost=stack_boost,
            )
            # Tech-stack-specific override for sqlmap extra_args
            if "sqli" in families and sqli_stack_args:
                _push({
                    "family": "sqli",
                    "target": url,
                    "target_param": p,
                    "rationale": f"Stack-aware SQLi probe on '{p}'. {rationale_stack}",
                    "evidence_signals": sorted(tech_stack & {"asp.net", "iis", "mssql", "php", "mysql", "mariadb"}),
                    "suggested_skill": "vuln-injection",
                    "suggested_tool": "sqlmap",
                    "suggested_extra_args": dict(sqli_stack_args),
                    "signal_expected": "WAITFOR DELAY/SLEEP latency >5s OU @@version visivel OU sqlmap 'injectable'",
                    "confidence": round(min(0.99, 0.85 + stack_boost), 2),
                    "id": _h_id("sqli-stack", url, p),
                })

    # Form inputs (from code-analyzer findings)
    # Each finding produced by code_analyzer.convert_to_findings carries
    # details.form_inputs when applicable.
    seen_form_params: set[tuple[str, str]] = set()
    for finding, _ in evidence_blobs:
        details = finding.get("details") or {}
        if not isinstance(details, dict):
            continue
        form_inputs = details.get("form_inputs") or []
        action_url = str(details.get("url") or details.get("asset") or "")
        if not action_url or not isinstance(form_inputs, list):
            continue
        for inp in form_inputs:
            if not isinstance(inp, dict):
                continue
            name = str(inp.get("name") or "").strip()
            input_type = str(inp.get("type") or "text").lower()
            if not name or input_type in {"submit", "button", "image", "reset", "hidden"}:
                # hidden inputs aren't user-controlled in the classic
                # sense but ASP.NET ViewState is — we still surface them
                # via Mass-assign probes (see H4 below).
                if input_type == "hidden":
                    continue
                continue
            if (action_url, name) in seen_form_params:
                continue
            seen_form_params.add((action_url, name))
            families = _families_for_param(name)
            if not families:
                families = {"sqli", "xss"}
            _push_matrix(
                target=action_url, param=name, families=families,
                rationale_extra=f"Form input no <form action={action_url}>. {rationale_stack}",
                confidence_boost=stack_boost,
            )

    # ── H2: HIDDEN PARAM PROBES — universal admin/debug/role probes ───────
    # Pensamento de pentest: mesmo sem evidencia, vale testar parametros
    # universais que app codes esquecem em prod (?debug=1, ?admin=1, etc).
    if urls:
        base_target = urls[0]
        for hp in HIDDEN_PARAM_PROBES:
            _push({
                "family": "info_disclosure",
                "target": base_target,
                "target_param": hp,
                "rationale": (
                    f"Hidden param probe universal: '{hp}' frequentemente exposto em prod "
                    f"(debug stacktraces, admin bypass, role escalation)."
                ),
                "evidence_signals": ["hidden_param_probe"],
                "suggested_skill": "vuln-information-disclosure",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": (
                    f"GET {base_target}?{hp}=1 retorna stacktrace OR resposta diferente da baseline"
                ),
                "confidence": 0.45,
                "id": _h_id("hidden", base_target, hp),
            })

    # ── H3: HEADER INJECTION MATRIX — toda iteracao injecta esses ─────────
    # X-Forwarded-For/Host, X-Original-URL, X-HTTP-Method-Override, etc.
    if urls:
        base_target = urls[0]
        for header_name, header_val in HEADER_INJECTION_MATRIX.items():
            # Map header to family for the right skill/tool
            if header_name.lower() in {"x-http-method-override", "x-method-override"}:
                fam = "auth_bypass"
            elif header_name.lower() == "user-agent":
                fam = "rce"  # Shellshock
            elif header_name.lower() in {"host", "x-forwarded-host"}:
                fam = "info_disclosure"  # cache poison / pwd reset poison
            elif header_name.lower() == "x-forwarded-for":
                fam = "auth_bypass"
            elif header_name.lower() in {"x-original-url", "x-rewrite-url"}:
                fam = "auth_bypass"
            elif header_name.lower() == "referer":
                fam = "xss"
            else:
                fam = "info_disclosure"
            recipe = FAMILY_RECIPES.get(fam, FAMILY_RECIPES["info_disclosure"])
            _push({
                "family": fam,
                "target": base_target,
                "target_param": f"header:{header_name}",
                "rationale": (
                    f"Header matrix: '{header_name}' frequentemente refletido sem sanitizar "
                    f"(cache poison, auth bypass, Shellshock dependendo do valor)."
                ),
                "evidence_signals": ["header_matrix"],
                "suggested_skill": recipe.get("skill"),
                "suggested_tool": recipe.get("tool"),
                "suggested_extra_args": dict(recipe.get("extra_args") or {}),
                "signal_expected": f"Resposta diferente da baseline quando {header_name}={header_val}",
                "confidence": 0.50,
                "id": _h_id("header", base_target, header_name),
            })

    # ── H4: VERB TAMPERING MATRIX — OPTIONS/PUT/DELETE/PATCH/TRACE ────────
    for url in urls[:5]:
        for verb in VERB_TAMPERING_PROBES:
            _push({
                "family": "auth_bypass",
                "target": url,
                "target_param": f"verb:{verb}",
                "rationale": (
                    f"Verb tampering: testar {verb} em {url}. Endpoints que aceitam apenas "
                    f"GET frequentemente caem com PUT/DELETE/PATCH sem checar autorizacao."
                ),
                "evidence_signals": ["verb_tampering"],
                "suggested_skill": "vuln-auth-bypass",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": f"Status 200/204 em {verb} {url} (deveria ser 405)",
                "confidence": 0.55,
                "id": _h_id("verb", url, verb),
            })

    # ── H5: IDOR / BOLA SEQUENTIAL PROBE ──────────────────────────────────
    # Para todo URL com param numerico (id/uid/pid/...), gerar uma hipotese
    # de IDOR sequencial (id=1, id=2, ..., id=999) procurando dados de
    # outro usuario. BOLA = mesmo conceito em REST/GraphQL.
    for url in urls:
        for p in _params_in_url(url):
            if not p:
                continue
            if not re.match(r"^(?:id|uid|pid|sid|cid|tid|user_?id|account_?id|order_?id|item_?id|product_?id|num)$", p, re.I):
                continue
            try:
                from urllib.parse import parse_qs, urlencode, urlparse, urlunparse
                parsed = urlparse(url)
                q = parse_qs(parsed.query)
                original_val = (q.get(p) or [""])[0]
            except Exception:
                original_val = ""
            _push({
                "family": "idor",
                "target": url,
                "target_param": p,
                "rationale": (
                    f"Param '{p}' numerico em {url} (original='{original_val}'). "
                    f"Testar IDOR/BOLA: trocar para id de outro usuario/objeto, checar se "
                    f"resposta retorna dados sem ownership-check."
                ),
                "evidence_signals": ["numeric_id_param", p],
                "suggested_skill": "vuln-idor-access-control",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": (
                    f"GET com {p}=1, {p}=2, {p}=999 retorna dados distintos sem 401/403 "
                    f"(IDOR confirmado). Tambem testar {p}=-1, {p}=0, {p}=00000."
                ),
                "confidence": 0.78,
                "id": _h_id("idor-seq", url, p),
            })

    # ── H6: MASS-ASSIGN PROBE — sempre que ha form POST ───────────────────
    for finding, _ in evidence_blobs:
        details = finding.get("details") or {}
        if not isinstance(details, dict):
            continue
        if str(details.get("form_method") or "").upper() not in {"POST", "PUT", "PATCH"}:
            continue
        action_url = str(details.get("url") or "")
        if not action_url:
            continue
        _push({
            "family": "mass_assign",
            "target": action_url,
            "target_param": "body",
            "rationale": (
                f"Form {str(details.get('form_method')).upper()} para {action_url}. "
                f"Testar mass-assignment: adicionar campos 'role=admin', 'isAdmin=true', "
                f"'is_verified=true', 'tenant_id=victim' ao body legitimo."
            ),
            "evidence_signals": ["form_post"],
            "suggested_skill": "vuln-auth-bypass",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": (
                "Campo malicioso ('role':'admin') persiste no perfil/objeto retornado"
            ),
            "confidence": 0.62,
            "id": _h_id("mass-assign", action_url, "body"),
        })

    # ── H7: CSRF — sempre que ha form sem token visivel ──────────────────
    for finding, _ in evidence_blobs:
        details = finding.get("details") or {}
        if not isinstance(details, dict):
            continue
        if str(details.get("form_method") or "").upper() not in {"POST", "PUT", "PATCH", "DELETE"}:
            continue
        inputs = details.get("form_inputs") or []
        if not isinstance(inputs, list):
            continue
        has_token = any(
            re.search(r"csrf|xsrf|antiforgery|_token", str(i.get("name") or ""), re.I)
            for i in inputs if isinstance(i, dict)
        )
        action_url = str(details.get("url") or "")
        if has_token or not action_url:
            continue
        _push({
            "family": "csrf",
            "target": action_url,
            "target_param": "form",
            "rationale": (
                f"Form mutante ({details.get('form_method')}) em {action_url} SEM CSRF token "
                "visivel nos inputs. Confirma CSRF se mudanca de state aceita sem token/SameSite."
            ),
            "evidence_signals": ["form_no_token"],
            "suggested_skill": "vuln-auth-bypass",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "Request cross-origin sem token muda estado (200 + persistido)",
            "confidence": 0.55,
            "id": _h_id("csrf", action_url, "form"),
        })

    # ── H8: AJAX endpoint exploration — GraphQL/REST sem param visivel ───
    for finding, _ in evidence_blobs:
        details = finding.get("details") or {}
        if not isinstance(details, dict):
            continue
        if str(details.get("kind") or "") != "ajax_endpoint":
            continue
        ep = str(details.get("url") or "")
        if not ep:
            continue
        # GraphQL detection
        if "graphql" in ep.lower():
            _push({
                "family": "graphql_introspection",
                "target": ep,
                "target_param": "query",
                "rationale": f"Endpoint GraphQL detectado: {ep}. Testar introspection + batched query DoS.",
                "evidence_signals": ["graphql_endpoint"],
                "suggested_skill": "vuln-api-graphql",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": "POST {query:'__schema{types{name}}'} retorna schema completo",
                "confidence": 0.82,
                "id": _h_id("graphql", ep, "query"),
            })
        # REST endpoint - probe BOLA (force-browse by id)
        if re.search(r"/api/.*/(users?|accounts?|orders?|items?|files?|documents?|messages?)(/|$)", ep, re.I):
            _push({
                "family": "bola",
                "target": ep,
                "target_param": "path-segment",
                "rationale": (
                    f"Endpoint REST object-based: {ep}. Testar BOLA — appendar /{{id}} de outro "
                    "usuario e checar se retorna dados sem ownership check."
                ),
                "evidence_signals": ["rest_object_endpoint"],
                "suggested_skill": "vuln-idor-access-control",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": "GET {ep}/<other-user-id> retorna 200 com dados sem 403",
                "confidence": 0.72,
                "id": _h_id("bola", ep, ""),
            })

    # ── H6: CORS misconfig (evidencia em header) ──────────────────────────
    if "access-control-allow-origin" in haystack and "access-control-allow-credentials" in haystack:
        _push({
            "family": "cors",
            "target": target or (urls[0] if urls else ""),
            "target_param": "",
            "rationale": "Evidencia de headers CORS na resposta — provavel reflexao de Origin com credentials.",
            "evidence_signals": ["access-control-allow-origin", "access-control-allow-credentials"],
            "suggested_skill": "tech-http-fingerprint",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "ACAO==Origin atacante AND ACAC=true",
            "confidence": 0.70,
        })

    # ── H7: Shellshock (cgi-bin no path) ──────────────────────────────────
    for url in urls:
        if "/cgi-bin/" in url.lower():
            _push({
                "family": "rce",
                "target": url,
                "target_param": "User-Agent",
                "rationale": "Caminho /cgi-bin/ encontrado — alvo classico Shellshock.",
                "evidence_signals": ["/cgi-bin/"],
                "suggested_skill": "vuln-injection",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": "() { :;}; echo retorna id no body OU pingback OOB",
                "confidence": 0.85,
            })

    # ── H8: WordPress (wpscan) ────────────────────────────────────────────
    if "wordpress" in tech_stack or "wp-content" in haystack or "wp-admin" in haystack:
        for url in urls[:3]:
            _push({
                "family": "cms",
                "target": url,
                "target_param": "",
                "rationale": "WordPress detectado (wp-content/wp-admin OU tech_stack).",
                "evidence_signals": ["wordpress"],
                "suggested_skill": "tech-cms-fingerprint",
                "suggested_tool": "wpscan",
                "suggested_extra_args": {"wpscan": ["--enumerate", "u,vp,vt", "--random-user-agent"]},
                "signal_expected": "Plugins vulneraveis, usuarios enumerados, xmlrpc accessible",
                "confidence": 0.90,
            })

    # ── H9: XXE (Content-Type XML aceito) ─────────────────────────────────
    if "application/xml" in haystack or "text/xml" in haystack or "soapaction" in haystack:
        _push({
            "family": "xxe",
            "target": target or (urls[0] if urls else ""),
            "target_param": "body (XML)",
            "rationale": "Servidor aceita Content-Type XML/SOAP — vetor XXE.",
            "evidence_signals": ["application/xml", "text/xml", "soapaction"],
            "suggested_skill": "vuln-injection",
            "suggested_tool": "wapiti",
            "suggested_extra_args": {"wapiti": ["-m", "xxe", "-f", "json"]},
            "signal_expected": "/etc/passwd no body OR callback OOB no interactsh",
            "confidence": 0.78,
        })

    # ── H10: Open redirect / CRLF (?next, redirect, with no SSRF tag) ─────
    # Already captured under H3 (ssrf family). Add a dedicated redirect H
    # for high-confidence Location-header reflection observed in evidence.
    if "location:" in haystack and ("redirect" in haystack or "location: http" in haystack):
        for url in urls[:2]:
            _push({
                "family": "redirect",
                "target": url,
                "target_param": "url|next|redirect",
                "rationale": "Header Location: aparece em evidencia + URL tem param de redirecionamento.",
                "evidence_signals": ["location:", "redirect"],
                "suggested_skill": "vuln-ssrf-redirect",
                "suggested_tool": "curl-headers",
                "suggested_extra_args": {},
                "signal_expected": "Location: para dominio externo do atacante",
                "confidence": 0.65,
            })

    # ── H11: SSTI (Jinja/Twig/Ruby template engine indicators) ────────────
    if any(s in haystack for s in ("jinja", "twig", "freemarker", "erb", "smarty", "x-powered-by: express")):
        _push({
            "family": "ssti",
            "target": target or (urls[0] if urls else ""),
            "target_param": "any reflected field",
            "rationale": "Engine de template detectado (Jinja/Twig/FreeMarker/ERB) — possivel SSTI.",
            "evidence_signals": ["jinja", "twig", "freemarker", "erb"],
            "suggested_skill": "vuln-injection",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "{{7*'7'}} renderiza 49 (Twig) ou 7777777 (Jinja)",
            "confidence": 0.70,
        })

    # ── H12: Information disclosure — .git/web.config/.env ────────────────
    if any(s in haystack for s in (".git", "web.config", ".env", "phpinfo", "stack trace")):
        _push({
            "family": "info_disclosure",
            "target": target or (urls[0] if urls else ""),
            "target_param": "",
            "rationale": "Evidencia de exposicao sensivel (.git/.env/web.config/stacktrace).",
            "evidence_signals": [".git", "web.config", ".env", "phpinfo"],
            "suggested_skill": "vuln-information-disclosure",
            "suggested_tool": "curl-headers",
            "suggested_extra_args": {},
            "signal_expected": "Status 200 em /.git/config OR /web.config OR /phpinfo.php",
            "confidence": 0.85,
        })

    return hypotheses


def hypothesis_for_skill(
    hypotheses: list[dict[str, Any]],
    *,
    skill_id: str | None = None,
    family: str | None = None,
) -> dict[str, Any] | None:
    """Return the highest-confidence hypothesis matching the filters, or None."""
    candidates = []
    for h in hypotheses or []:
        if skill_id and str(h.get("suggested_skill") or "") != skill_id:
            continue
        if family and str(h.get("family") or "") != family:
            continue
        candidates.append(h)
    candidates.sort(key=lambda x: -float(x.get("confidence") or 0))
    return candidates[0] if candidates else None


def hypothesis_to_tactic(h: dict[str, Any], capability: str = "risk_assessment") -> dict[str, Any]:
    """Materialise a hypothesis as a pentest tactic the supervisor can lock to."""
    return {
        "tactic_id": f"hypothesis:{h['family']}:{h['id']}",
        "skill_id": str(h.get("suggested_skill") or "vuln-injection"),
        "capability": capability,
        "objective": h.get("rationale", ""),
        "hypothesis": h.get("rationale", ""),
        "allowed_tools": [str(h.get("suggested_tool") or "")],
        "preferred_tool": str(h.get("suggested_tool") or ""),
        "extra_args": dict(h.get("suggested_extra_args") or {}),
        "strategy_source": "hypothesis_engine",
        "strategy_score": int(round(float(h.get("confidence") or 0) * 100)),
        "learning_techniques": [],
        "evidence_required": [h.get("signal_expected", "")],
        "constraints": [],
        "phase_refs": [],
        "targets": [str(h.get("target") or "")] if h.get("target") else [],
        "reason": (
            f"Hipotese {h.get('family')} sobre {h.get('target')}"
            + (f"?{h.get('target_param')}=" if h.get("target_param") else "")
            + f" — {h.get('rationale','')} (confidence={h.get('confidence',0):.2f})"
        ),
    }
