"""sync_model_columns

Revision ID: 36258e602bd7
Revises: 0010_scan_job_last_error
Create Date: 2026-05-13 21:27:50.107659
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '36258e602bd7'
down_revision = '0010_scan_job_last_error'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_groups_owner_id'), 'access_groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    op.create_index(op.f('ix_app_settings_owner_id'), 'app_settings', ['owner_id'], unique=False)
    op.drop_index('ix_asset_rating_history_asset_recorded_at', table_name='asset_rating_history')
    op.create_index(op.f('ix_asset_rating_history_id'), 'asset_rating_history', ['id'], unique=False)
    op.drop_index('ix_assets_criticality', table_name='assets', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index('ix_assets_owner_status', table_name='assets')
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_scan_job_id'), 'audit_events', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_client_policies_owner_id'), 'client_policies', ['owner_id'], unique=False)
    op.drop_index('ix_easm_alert_rules_owner_enabled', table_name='easm_alert_rules')
    op.create_index(op.f('ix_easm_alert_rules_id'), 'easm_alert_rules', ['id'], unique=False)
    op.alter_column('easm_alerts', 'webhook_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_easm_alerts_owner_resolved', table_name='easm_alerts')
    op.create_index(op.f('ix_easm_alerts_id'), 'easm_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_executed_tool_runs_id'), 'executed_tool_runs', ['id'], unique=False)
    op.create_unique_constraint('uq_executed_tool_runs_scan_tool_target', 'executed_tool_runs', ['scan_job_id', 'tool_name', 'target'])
    op.create_index(op.f('ix_false_positive_memory_signature'), 'false_positive_memory', ['signature'], unique=False)
    op.add_column('findings', sa.Column('sn1per_priority', sa.String(length=10), nullable=True))
    op.add_column('findings', sa.Column('confidence_score', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('findings', sa.Column('fp_notes', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('fp_reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('fp_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('findings', sa.Column('retest_status', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_findings_retest_status'), 'findings', ['retest_status'], unique=False)
    op.create_index(op.f('ix_findings_scan_job_id'), 'findings', ['scan_job_id'], unique=False)
    op.create_foreign_key(None, 'findings', 'users', ['fp_reviewed_by_id'], ['id'])
    op.create_index(op.f('ix_operation_lines_owner_id'), 'operation_lines', ['owner_id'], unique=False)
    op.create_index(op.f('ix_policy_allowlist_entries_policy_id'), 'policy_allowlist_entries', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_allowlist_entries_target_pattern'), 'policy_allowlist_entries', ['target_pattern'], unique=False)
    op.create_index(op.f('ix_scan_audit_logs_id'), 'scan_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_authorizations_requester_id'), 'scan_authorizations', ['requester_id'], unique=False)
    op.create_index(op.f('ix_scan_authorizations_target_query'), 'scan_authorizations', ['target_query'], unique=False)
    op.create_index(op.f('ix_scan_jobs_access_group_id'), 'scan_jobs', ['access_group_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_authorization_code'), 'scan_jobs', ['authorization_code'], unique=False)
    op.create_index(op.f('ix_scan_jobs_authorization_id'), 'scan_jobs', ['authorization_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_owner_id'), 'scan_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_target_query'), 'scan_jobs', ['target_query'], unique=False)
    op.create_index(op.f('ix_scan_logs_created_at'), 'scan_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_logs_scan_job_id'), 'scan_logs', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_scheduled_scans_access_group_id'), 'scheduled_scans', ['access_group_id'], unique=False)
    op.create_index(op.f('ix_scheduled_scans_authorization_code'), 'scheduled_scans', ['authorization_code'], unique=False)
    op.create_index(op.f('ix_scheduled_scans_owner_id'), 'scheduled_scans', ['owner_id'], unique=False)
    op.drop_index('ix_vulnerabilities_fair_pillar', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_remediated_at', table_name='vulnerabilities', postgresql_where='(remediated_at IS NOT NULL)')
    op.drop_index('ix_vulnerabilities_severity', table_name='vulnerabilities')
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.create_index('ix_vulnerabilities_severity', 'vulnerabilities', ['severity'], unique=False)
    op.create_index('ix_vulnerabilities_remediated_at', 'vulnerabilities', ['remediated_at'], unique=False, postgresql_where='(remediated_at IS NOT NULL)')
    op.create_index('ix_vulnerabilities_fair_pillar', 'vulnerabilities', ['fair_pillar'], unique=False)
    op.drop_index(op.f('ix_scheduled_scans_owner_id'), table_name='scheduled_scans')
    op.drop_index(op.f('ix_scheduled_scans_authorization_code'), table_name='scheduled_scans')
    op.drop_index(op.f('ix_scheduled_scans_access_group_id'), table_name='scheduled_scans')
    op.drop_index(op.f('ix_scan_logs_scan_job_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_created_at'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_jobs_target_query'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_owner_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_authorization_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_authorization_code'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_access_group_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_authorizations_target_query'), table_name='scan_authorizations')
    op.drop_index(op.f('ix_scan_authorizations_requester_id'), table_name='scan_authorizations')
    op.drop_index(op.f('ix_scan_audit_logs_id'), table_name='scan_audit_logs')
    op.drop_index(op.f('ix_policy_allowlist_entries_target_pattern'), table_name='policy_allowlist_entries')
    op.drop_index(op.f('ix_policy_allowlist_entries_policy_id'), table_name='policy_allowlist_entries')
    op.drop_index(op.f('ix_operation_lines_owner_id'), table_name='operation_lines')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_index(op.f('ix_findings_scan_job_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_retest_status'), table_name='findings')
    op.drop_column('findings', 'retest_status')
    op.drop_column('findings', 'fp_reviewed_at')
    op.drop_column('findings', 'fp_reviewed_by_id')
    op.drop_column('findings', 'fp_notes')
    op.drop_column('findings', 'confidence_score')
    op.drop_column('findings', 'sn1per_priority')
    op.drop_index(op.f('ix_false_positive_memory_signature'), table_name='false_positive_memory')
    op.drop_constraint('uq_executed_tool_runs_scan_tool_target', 'executed_tool_runs', type_='unique')
    op.drop_index(op.f('ix_executed_tool_runs_id'), table_name='executed_tool_runs')
    op.drop_index(op.f('ix_easm_alerts_id'), table_name='easm_alerts')
    op.create_index('ix_easm_alerts_owner_resolved', 'easm_alerts', ['owner_id', 'is_resolved'], unique=False)
    op.alter_column('easm_alerts', 'webhook_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_easm_alert_rules_id'), table_name='easm_alert_rules')
    op.create_index('ix_easm_alert_rules_owner_enabled', 'easm_alert_rules', ['owner_id', 'enabled'], unique=False)
    op.drop_index(op.f('ix_client_policies_owner_id'), table_name='client_policies')
    op.drop_index(op.f('ix_audit_events_scan_job_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.create_index('ix_assets_owner_status', 'assets', ['owner_id', 'status'], unique=False)
    op.create_index('ix_assets_criticality', 'assets', ['criticality_score'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_asset_rating_history_id'), table_name='asset_rating_history')
    op.create_index('ix_asset_rating_history_asset_recorded_at', 'asset_rating_history', ['asset_id', 'recorded_at'], unique=False)
    op.drop_index(op.f('ix_app_settings_owner_id'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index(op.f('ix_access_groups_owner_id'), table_name='access_groups')
    # ### end Alembic commands ###
